//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Botvinko_VE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class botvinkoEntities : DbContext
    {
        public botvinkoEntities()
            : base("name=botvinkoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cleaning_shedule> Cleaning_shedule { get; set; }
        public virtual DbSet<Guests> Guests { get; set; }
        public virtual DbSet<Guests_services> Guests_services { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Reservations> Reservations { get; set; }
        public virtual DbSet<Room_accsess> Room_accsess { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
